#include "vita_native_save_policy.h"

#include <stdio.h>
#include <string.h>

static void set_reason(char *out_reason, size_t out_reason_size, const char *reason) {
  if ((out_reason == NULL) || (out_reason_size == 0U)) {
    return;
  }

  snprintf(out_reason, out_reason_size, "%s", reason != NULL ? reason : "");
}

int vita_native_save_container_is_exportable(
    int has_sce_sys,
    int has_keystone,
    int has_param_sfo,
    char *out_reason,
    size_t out_reason_size) {
  if (!has_sce_sys) {
    set_reason(out_reason, out_reason_size, "missing sce_sys metadata directory");
    return 0;
  }
  if (!has_param_sfo) {
    set_reason(out_reason, out_reason_size, "missing PARAM.SFO metadata");
    return 0;
  }
  if (!has_keystone) {
    set_reason(out_reason, out_reason_size, "missing keystone signature metadata required by Vita PFS");
    return 0;
  }

  set_reason(out_reason, out_reason_size, "exportable signed Vita container with keystone metadata");
  return 1;
}

static char ascii_upper(char value) {
  if ((value >= 'a') && (value <= 'z')) {
    return (char)(value - ('a' - 'A'));
  }
  return value;
}

static int ascii_digit(char value) {
  return (value >= '0') && (value <= '9');
}

int vita_native_save_title_id_is_official_game(const char *title_id) {
  if (title_id == NULL) {
    return 0;
  }

  if ((ascii_upper(title_id[0]) != 'P') ||
      (ascii_upper(title_id[1]) != 'C') ||
      (ascii_upper(title_id[2]) != 'S')) {
    return 0;
  }

  char region = ascii_upper(title_id[3]);
  if ((region < 'A') || (region > 'H')) {
    return 0;
  }

  for (int i = 4; i < 9; ++i) {
    if (!ascii_digit(title_id[i])) {
      return 0;
    }
  }

  return title_id[9] == '\0';
}

const char *vita_native_save_restore_safety_notice(void) {
  return "native Vita restore uses raw PFS archives only: validate TITLE_ID and keystone, back up the current container, then replace the savedata directory";
}

const char *vita_native_save_vita3k_import_notice(void) {
  return "native Vita archives are not direct Vita3K imports: use VitaShell Open decrypted "
         "or a Vita save manager to export decrypted data, then copy the decrypted save "
         "payload into Vita3K while keeping the SlotParam_*.bin generated by Vita3K";
}

static int ascii_char_ieq(char lhs, char rhs) {
  return ascii_upper(lhs) == ascii_upper(rhs);
}

static int has_tar_extension(const char *name, size_t length) {
  return (name != NULL) && (length > 4U) &&
         (name[length - 4U] == '.') &&
         ascii_char_ieq(name[length - 3U], 't') &&
         ascii_char_ieq(name[length - 2U], 'a') &&
         ascii_char_ieq(name[length - 1U], 'r');
}

int vita_native_save_archive_timestamp_from_filename(
    const char *filename,
    int64_t *out_timestamp_unix) {
  if ((filename == NULL) || (out_timestamp_unix == NULL)) {
    return -1;
  }

  const char *base = filename;
  for (const char *cursor = filename; *cursor != '\0'; ++cursor) {
    if ((*cursor == '/') || (*cursor == '\\')) {
      base = cursor + 1;
    }
  }

  size_t length = strlen(base);
  if (!has_tar_extension(base, length) || (length <= 14U) || (base[9] != '_')) {
    return -1;
  }

  char title_id[10];
  memcpy(title_id, base, 9U);
  title_id[9] = '\0';
  if (!vita_native_save_title_id_is_official_game(title_id)) {
    return -1;
  }

  size_t name_length = length - 4U;
  size_t timestamp_start = 10U;
  for (size_t i = 10U; i < name_length; ++i) {
    if (base[i] == '_') {
      timestamp_start = i + 1U;
    }
  }
  if (timestamp_start >= name_length) {
    return -1;
  }

  int64_t value = 0;
  for (size_t i = timestamp_start; i < name_length; ++i) {
    if (!ascii_digit(base[i])) {
      return -1;
    }
    int digit = base[i] - '0';
    if (value > ((INT64_MAX - digit) / 10)) {
      return -1;
    }
    value = (value * 10) + digit;
  }

  if (value <= 0) {
    return -1;
  }

  *out_timestamp_unix = value;
  return 0;
}
