site_name: RoMM Vita Sync
site_url: https://sangimed.github.io/romm-vita-sync/
docs_dir: docs
theme:
  name: material
  features:
    - toc.integrate
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
plugins:
  - search
  - mike:
      alias_type: redirect
extra:
  version:
    provider: mike
    default: stable
nav:
  - Home: index.md
